import {
  Shield,
  Lock,
  Globe,
  Usb,
  Download,
  Cpu,
  AlertTriangle,
  Terminal,
  CheckCircle2,
  XCircle,
  Play,
  Copy,
  LayoutTemplate,
  Save,
  Wand2,
  Unlock,
  Settings,
  Activity,
  Monitor,
  Moon,
  BellOff,
  MousePointer2,
  RefreshCwOff,
  EyeOff,
  HelpCircle,
  Package,
  Ban,
  Sliders,
  UserX,
  Puzzle,
  Printer,
  UploadCloud,
  User,
  Linkedin,
  Github,
  ExternalLink,
  Phone,
  Sun,
  CreditCard,
  RotateCcw,
  ShieldAlert,
  WifiOff,
  Mail,
  MapPin,
  Heart,
  Star
} from 'lucide-react';


export const ICONS = {
  Shield,
  Lock,
  Globe,
  Usb,
  Download,
  Cpu,
  AlertTriangle,
  Terminal,
  CheckCircle2,
  XCircle,
  Play,
  Copy,
  LayoutTemplate,
  Save,
  Wand2,
  Unlock,
  Settings,
  Activity,
  Monitor,
  Moon,
  Sun,
  BellOff,
  MousePointer2,
  RefreshCwOff,
  EyeOff,
  HelpCircle,
  Package,
  Ban,
  Sliders,
  UserX,
  Puzzle,
  Printer,
  UploadCloud,
  User,
  Linkedin,
  Github,
  ExternalLink,
  Mail,
  Phone,
  CreditCard,
  RotateCcw,
  ShieldAlert,
  WifiOff,
  MapPin,
  Heart,
  Star,
};

export const COMMON_BROWSERS = [
  "chrome.exe",
  "firefox.exe",
  "brave.exe",
  "opera.exe",
  "opera_launcher.exe",
  "vivaldi.exe",
  "tor.exe",
  "browser.exe"
];

export const INITIAL_STATE = {
  system: {
    blockUsb: false,
    blockStore: false,
    blockExecutables: false,
    strictMode: false,
    allowPeripherals: false,
  },
  advanced: {
    blockTaskMgr: false,
    blockCmdPowershell: false,
    blockSettings: false,
    blockControlPanel: false,
    blockRegistryTools: false,
    blockSpecificApps: false,
    blockedAppList: [],
    preventUacBypass: false,
    isolateUserFolders: false,
  },
  kiosk: {
    disableWindowsUpdate: false,
    disableSleep: false,
    hideDesktopIcons: false,
    disableContextMenu: false,
    disableNotifications: false,
    disableTelemetry: false,
  },
  web: {
    enforceEdge: false,
    urlFilterMode: 'whitelist' as 'whitelist' | 'blocklist',
    allowedUrls: [],
    blockedUrls: [
      // --- File Upload & Cloud Storage Sites ---
      'drive.google.com',
      'dropbox.com',
      'onedrive.live.com',
      'icloud.com',
      'mega.nz',
      'wetransfer.com',
      'box.com',
      'pcloud.com',
      'mediafire.com',
      'sync.com',
      'proton.me',
      'terabox.com',
      'swisstransfer.com',
      'transfernow.net',
      'gofile.io',
      'idrive.com',
      'filemail.com',
      'hightail.com',
      'send-anywhere.com',
      'icedrive.net',
      'jumpshare.com',
      'internxt.com',
      'sugarsync.com',
      'sharefile.com',
      '4shared.com',
      'slideshare.net',
      'scribd.com',
      'issuu.com',
      'hidrive.com',
      'collabow.io',
      // --- Social Media Sites ---
      'facebook.com',
      'youtube.com',
      'whatsapp.com',
      'instagram.com',
      'tiktok.com',
      'wechat.com',
      'linkedin.com',
      'telegram.org',
      'x.com',
      'twitter.com',
      'reddit.com',
      'snapchat.com',
      'pinterest.com',
      'threads.net',
      'discord.com',
      'twitch.tv',
      'tumblr.com',
      'quora.com',
      'bsky.app',
      'mastodon.social',
      'bereal.com',
      'lemon8-app.com',
      'substack.com',
      'rumble.com',
      'vk.com',
      'line.me',
      'viber.com',
      'nextdoor.com',
      'meetup.com',
      'flickr.com',
      'xiaohongshu.com',
    ],
    allowedExtensions: [
      'ddkjiahejlhfcafbddmgiahcphecmpfh',
      'alhgpfoeiimagjlnfekdhkjlkiomcapa',
      'mcebeofpilippmndlpcghpmghcljajna',
      'oiecklaabeielolbliiddlbokpfnmhba',
      'aapbdbdomjkkjkaonfhkkikfgjllcleb',
      'omojcahabhafmagldeheegggbakefhlh',
    ],
    allowPdfView: true,
    blockFileUploads: false,
    forceStartup: false,
    blockOtherBrowsers: false,
    allowPasswordManager: false,
    forceSmartScreen: true,
    forceDns: false,
  },
};