import {
  Shield,
  Lock,
  Globe,
  Usb,
  Download,
  Cpu,
  AlertTriangle,
  Terminal,
  CheckCircle2,
  XCircle,
  Play,
  Copy,
  LayoutTemplate,
  Save,
  Wand2,
  Unlock,
  Settings,
  Activity,
  Monitor,
  Moon,
  BellOff,
  MousePointer2,
  RefreshCwOff,
  EyeOff,
  HelpCircle,
  Package,
  Ban,
  Sliders,
  UserX,
  Puzzle,
  Printer,
  UploadCloud,
  User,
  Linkedin,
  Github,
  ExternalLink,
  Phone,
  Sun,
  CreditCard,
  RotateCcw,
  ShieldAlert,
  WifiOff,
  Mail,
  MapPin,
  Heart,
  Star
} from 'lucide-react';


export const ICONS = {
  Shield,
  Lock,
  Globe,
  Usb,
  Download,
  Cpu,
  AlertTriangle,
  Terminal,
  CheckCircle2,
  XCircle,
  Play,
  Copy,
  LayoutTemplate,
  Save,
  Wand2,
  Unlock,
  Settings,
  Activity,
  Monitor,
  Moon,
  Sun,
  BellOff,
  MousePointer2,
  RefreshCwOff,
  EyeOff,
  HelpCircle,
  Package,
  Ban,
  Sliders,
  UserX,
  Puzzle,
  Printer,
  UploadCloud,
  User,
  Linkedin,
  Github,
  ExternalLink,
  Mail,
  Phone,
  CreditCard,
  RotateCcw,
  ShieldAlert,
  WifiOff,
  MapPin,
  Heart,
  Star,
};

export const COMMON_BROWSERS = [
  "chrome.exe",
  "firefox.exe",
  "brave.exe",
  "opera.exe",
  "opera_launcher.exe",
  "vivaldi.exe",
  "tor.exe",
  "browser.exe"
];

export const INITIAL_STATE = {
  system: {
    blockUsb: false,
    blockStore: false,
    blockExecutables: false,
    strictMode: false,
    allowPeripherals: false,
  },
  advanced: {
    blockTaskMgr: false,
    blockCmdPowershell: false,
    blockSettings: false,
    blockControlPanel: false,
    blockRegistryTools: false,
    blockSpecificApps: false,
    blockedAppList: [],
    preventUacBypass: false,
    isolateUserFolders: false,
  },
  kiosk: {
    disableWindowsUpdate: false,
    disableSleep: false,
    hideDesktopIcons: false,
    disableContextMenu: false,
    disableNotifications: false,
    disableTelemetry: false,
  },
  web: {
    enforceEdge: false,
    allowedUrls: [],
    allowedExtensions: [],
    allowPdfView: true,
    whitelistOnly: true, // Default to strict kiosk mode
    blockFileUploads: false,
    forceStartup: false,
    blockOtherBrowsers: false,
    allowPasswordManager: false,
    forceSmartScreen: true, // Security best practice
  },
};